In [24]:
import numpy as np
import json

## random 8 pop para

In [37]:
pops = np.array([20683, 5834, 21915, 5479, 4850, 1065, 14395, 2948])
pops_prop = np.random.choice([1, -1], size=len(pops)) # 1: excitatory, -1: inhibitory

pconn = np.random.randint(0, 2, (len(pops), len(pops)))
np.fill_diagonal(pconn, 1)

J = np.random.uniform(0.06, 0.3)  # excitatory synaptic weight in mV, w^{αβ} in the paper
g = np.random.uniform(3, 5)   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn * np.random.uniform(0.5, 1.5, (len(pops), len(pops)))

pconn_coeff = np.array([
    [0.1009, 0.1689, 0.0437, 0.0818, 0.0323, 0, 0.0076, 0],
    [0.1346, 0.1371, 0.0316, 0.0515, 0.0755, 0, 0.0042, 0],
    [0.0077, 0.0059, 0.0497, 0.135, 0.0067, 0.0003, 0.0453, 0],
    [0.0691, 0.0029, 0.0794, 0.1597, 0.0033, 0, 0.1057, 0],
    [0.1004, 0.0622, 0.0505, 0.0057, 0.0831, 0.3726, 0.0204, 0],
    [0.0548, 0.0269, 0.0257, 0.0022, 0.06, 0.3158, 0.0086, 0],
    [0.0156, 0.0066, 0.0211, 0.0166, 0.0572, 0.0197, 0.0396, 0.2252],
    [0.0364, 0.001, 0.0034, 0.0005, 0.0277, 0.008, 0.0658, 0.1443]
])
pconn = pconn * pconn_coeff

mu = np.random.uniform(20, 60, len(pops)) # V_rest + I_external * R
tau_m = np.random.uniform(10, 40, len(pops))  # membrane time constant
V_th = np.random.uniform(10, 30, len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [np.random.uniform(0, 1500)]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [np.random.uniform(0, 1500)]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [np.random.uniform(0, 1500)]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [np.random.uniform(0, 1500)]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

In [38]:
print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

J_syn_list = J_syn.tolist()
mu_list = mu.tolist()
tau_m_list = tau_m.tolist()
V_th_list = V_th.tolist()
J_theta_list = J_theta.tolist()
tau_theta_list = tau_theta.tolist()

setting = 1
seed_num = 1

# Store your data into a dictionary
data_dict = {"setting": setting, 
        "seed_num": seed_num, 
        "J_syn": J_syn_list, 
        "mu": mu_list, 
        "tau_m": tau_m_list, 
        "V_th": V_th_list, 
        "J_theta": J_theta_list, 
        "tau_theta": tau_theta_list
        }

# Convert the dictionary into a JSON string
json_str = json.dumps(data_dict)

# Create the file name string
filename = f"data_{setting}-{seed_num}.json"

# Write the JSON string to a file
with open(filename, 'w') as json_file:
    json_file.write(json_str)


# Read the JSON string from the file
with open(filename, 'r') as json_file:
    json_str = json_file.read()

# Convert the JSON string into a dictionary
data_dict = json.loads(json_str)

# Convert the nested lists back into numpy arrays
J_syn = np.array(data_dict["J_syn"])
mu = np.array(data_dict["mu"])
tau_m = np.array(data_dict["tau_m"])
V_th = np.array(data_dict["V_th"])
J_theta = np.array(data_dict["J_theta"])
tau_theta = np.array(data_dict["tau_theta"])

print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

print(data_dict)

[[ 0.15100963  0.         -0.         -0.73659288  0.10340389  0.
  -0.43375748 -0.76296671]
 [ 0.          0.10293862 -0.72453475 -0.50927912  0.06557972  0.
  -0.66696421 -0.        ]
 [ 0.16327811  0.14064248 -0.36831358 -0.          0.          0.12718346
  -0.66777753 -0.        ]
 [ 0.05874833  0.         -0.38153315 -0.42956491  0.          0.07120331
  -0.         -0.37005946]
 [ 0.          0.         -0.         -0.          0.14886066  0.
  -0.4591437  -0.        ]
 [ 0.          0.12166809 -0.42418922 -0.61401393  0.08593424  0.0603415
  -0.41631874 -0.        ]
 [ 0.14118131  0.08548182 -0.30045833 -0.          0.14422604  0.
  -0.7611016  -0.38772028]
 [ 0.11793987  0.08911273 -0.77923394 -0.          0.          0.
  -0.         -0.55109108]]
[41.12582985 50.1056665  51.45972527 24.07675962 50.14156835 40.70714351
 59.67498722 39.85802266]
[24.39332891 22.49451106 17.28022169 36.99383079 29.56238494 32.6761351
 20.18460807 17.22108952]
[22.90644944 18.27305909 15.0359733

## random 3 pop para

In [ ]:
pops = np.array([400, 200, 400])
pops_prop = np.random.choice([1, -1], size=len(pops)) # 1: excitatory, -1: inhibitory

pconn = np.random.randint(0, 2, (len(pops), len(pops)))
np.fill_diagonal(pconn, 1)

J = np.random.uniform(0.06, 0.3)  # excitatory synaptic weight in mV, w^{αβ} in the paper
g = np.random.uniform(3, 6)   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn * np.random.uniform(0.5, 1.5, (len(pops), len(pops)))

pconn_coeff = 0.6
pconn = pconn * pconn_coeff

mu = np.random.uniform(20, 60, len(pops)) # V_rest + I_external * R
tau_m = np.random.uniform(10, 40, len(pops))  # membrane time constant
V_th = np.random.uniform(10, 30, len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [np.random.uniform(80, 1500)]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [np.random.uniform(80, 1500)]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [np.random.uniform(80, 1500)]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [np.random.uniform(80, 1500)]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

In [ ]:
print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

J_syn_list = J_syn.tolist()
mu_list = mu.tolist()
tau_m_list = tau_m.tolist()
V_th_list = V_th.tolist()
J_theta_list = J_theta.tolist()
tau_theta_list = tau_theta.tolist()

setting = 1
seed_num = 1

# Store your data into a dictionary
data_dict = {"setting": setting, 
        "seed_num": seed_num, 
        "J_syn": J_syn_list, 
        "mu": mu_list, 
        "tau_m": tau_m_list, 
        "V_th": V_th_list, 
        "J_theta": J_theta_list, 
        "tau_theta": tau_theta_list
        }

# Convert the dictionary into a JSON string
json_str = json.dumps(data_dict)

# Create the file name string
filename = f"data_{setting}-{seed_num}.json"

# Write the JSON string to a file
with open(filename, 'w') as json_file:
    json_file.write(json_str)


# Read the JSON string from the file
with open(filename, 'r') as json_file:
    json_str = json_file.read()

# Convert the JSON string into a dictionary
data_dict = json.loads(json_str)

# Convert the nested lists back into numpy arrays
J_syn = np.array(data_dict["J_syn"])
mu = np.array(data_dict["mu"])
tau_m = np.array(data_dict["tau_m"])
V_th = np.array(data_dict["V_th"])
J_theta = np.array(data_dict["J_theta"])
tau_theta = np.array(data_dict["tau_theta"])

print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

print(data_dict)

[[ 0.24724725 -0.          0.        ]
 [ 0.         -0.58247619  0.        ]
 [ 0.         -0.          0.1521292 ]]
[54.6528744  30.81797719 30.5206559 ]
[36.24766555 21.45326659 25.40004589]
[14.04083336 25.41295085 27.62235758]
[[1383.44940246]
 [ 447.57197117]
 [1383.44940246]]
[[ 942.37085234]
 [1077.55660579]
 [ 942.37085234]]
-- -- --
[[ 0.24724725 -0.          0.        ]
 [ 0.         -0.58247619  0.        ]
 [ 0.         -0.          0.1521292 ]]
[54.6528744  30.81797719 30.5206559 ]
[36.24766555 21.45326659 25.40004589]
[14.04083336 25.41295085 27.62235758]
[[1383.44940246]
 [ 447.57197117]
 [1383.44940246]]
[[ 942.37085234]
 [1077.55660579]
 [ 942.37085234]]
-- -- --
{'setting': 1, 'seed_num': 1, 'J_syn': [[0.24724724919346042, -0.0, 0.0], [0.0, -0.5824761916708973, 0.0], [0.0, -0.0, 0.15212919967157734]], 'mu': [54.65287439733692, 30.817977191412638, 30.520655897465833], 'tau_m': [36.247665546867466, 21.453266587341155, 25.40004588914421], 'V_th': [14.040833361554334, 25

## 3 pops parameter setting

In [ ]:
pops = np.array([400, 200, 400])
pops_prop = np.array([1, -1, 1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1, 0],
          [1, 1, 1],
          [0, 1, 1]])
J = 0.0624  # excitatory synaptic weight in mV 
g = 0.496/0.0624   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 1
pconn = pconn * pconn_coeff

mu = 36 * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20 * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [1000., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [1000., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [100., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [100., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

## Bistability para

In [ ]:
pops = np.array([400, 200, 400])
pops_prop = np.array([1, -1, 1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1, 0],
          [1, 1, 1],
          [0, 1, 1]])
J = 0.096  # excitatory synaptic weight in mV
g = 0.384/0.096   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 1.
pconn = pconn * pconn_coeff

mu = 36. * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20. * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [100.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [100.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

## original para

In [ ]:
pops = np.array([800, 200])
pops_prop = np.array([1, -1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1],
          [1, 1]])
J = 0.3  # excitatory synaptic weight in mV 
g = 5   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 0.2
pconn = pconn * pconn_coeff

mu = 24 * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20 * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [100., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [100., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [1000., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [1000., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

## other para

In [ ]:
pops = np.array([800, 200])
pops_prop = np.array([1, -1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1],
          [1, 1]])
J = 0.3  # excitatory synaptic weight in mV, w^{αβ} in the paper
g = 5.   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 0.2
pconn = pconn * pconn_coeff

mu = 24. * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20. * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [100., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [100., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [1000., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [1000., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

In [ ]:
pops = np.array([800, 200, 200])
pops_prop = np.array([1, -1, 1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]])
J = 0.3  # excitatory synaptic weight in mV 
g = 5.   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 0.2
pconn = pconn * pconn_coeff

mu = 24 * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20 * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [100., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [100., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [1000., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [1000., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])